### ISSUE TITLE
Building O2 on slc6 fails while building FairRoot

### ISSUE THREAD

**Issue by vascobarroso** [alisw/alidist#252]
Log file here: [log.txt](https://github.com/alisw/alidist/files/176411/log.txt)

**Comment by ktf** [comment]
You have SIMPATH set, right? That confuses FairROOT builds as it mixes old and new ways of building. Can you unset it?

**Comment by ktf** [comment]
Hopefully fixed by #254

**Comment by vascobarroso** [comment]
Now it goes a bit further, but still fails:

[log.txt](https://github.com/alisw/alidist/files/177902/log.txt)
[CMakeError.log.txt](https://github.com/alisw/alidist/files/177907/CMakeError.log.txt)
[CMakeOutput.log.txt](https://github.com/alisw/alidist/files/177906/CMakeOutput.log.txt)

Do you want a separate issue ?

**Comment by ktf** [comment]
It's fine here. I can spin off new issues if necessary.

**Comment by ktf** [comment]
Looks like there is something wrong with picking up zeromq.

**Comment by ktf** [comment]
Can you tell me what::

```
printf "#include \"zmq.h\"\n" | gcc -I$(brew --prefix zeromq)/include -xc++ - -c -M
```

tells you?

**Comment by ktf** [comment]
Alternatively can you pull the latest changes from both alibuild and alidist and simply run:

```
alibuild/aliDoctor
```

**Comment by vascobarroso** [comment]
I'm running a standard SLC6 installation, so no brew...
I've updated alibuild, but there's no aliDoctor...

Here's what RPM says about zeromq installation:

```
[vasco@aidrefflp01 alice]$ rpmquery -l zeromq4
/usr/bin/curve_keygen
/usr/lib64/libzmq.so.5
/usr/lib64/libzmq.so.5.0.0
/usr/share/doc/zeromq4-4.1.4
/usr/share/doc/zeromq4-4.1.4/AUTHORS
/usr/share/doc/zeromq4-4.1.4/COPYING
/usr/share/doc/zeromq4-4.1.4/COPYING.LESSER
/usr/share/doc/zeromq4-4.1.4/ChangeLog
/usr/share/doc/zeromq4-4.1.4/NEWS
```

**Comment by ktf** [comment]
Missing brew is not an issue.

aliDoctor is in the `next` branch. Can you please do:

    git pull upstream next

and try again?

**Comment by vascobarroso** [comment]
```
git pull origin next 
```

did the trick. Here's the output of aliDoctor:

```
[vasco@aidrefflp01 alice]$ ./alibuild/aliDoctor 
bz2:printf "#include <bzlib.h>\n" | gcc -xc++ - -c -o /dev/null
bz2:
bz2: exit code 0
PCRE:printf "#include \"pcre.h\"\n" | gcc -I`brew --prefix pcre`/include -xc++ - -c -o /dev/null
/bin/sh: brew: command not found
<stdin>:1:18: fatal error: pcre.h: No such file or directory
compilation terminated.
PCRE:
PCRE: exit code 1
ZeroMQ:printf "#include \"zmq.h\"\n" | gcc -I$(brew --prefix zeromq)/include -xc++ - -c -o /dev/null
/bin/sh: brew: command not found
ZeroMQ:
ZeroMQ: exit code 0
yaml-cpp:printf "#include \"yaml-cpp/yaml.h\"\n" | gcc -I`brew --prefix yaml-cpp`/include -I`brew --prefix boost`/include -xc++ - -c -o /dev/null
/bin/sh: brew: command not found
/bin/sh: brew: command not found
<stdin>:1:27: fatal error: yaml-cpp/yaml.h: No such file or directory
compilation terminated.
yaml-cpp:
yaml-cpp: exit code 1
CMake:which cmake && case `cmake --version | sed -e 's/.* //' | cut -d. -f1,2,3 | head -n1` in [0-1]*|2.[0-7].*|2.8.[0-9]|2.8.1[0-1]) exit 1 ;; esac
CMake:/usr/bin/cmake
CMake:
CMake: exit code 0
OpenSSL:echo '#include <openssl/bio.h>' | c++ -x c++ - -I`brew --prefix openssl`/include -c -o /dev/null
/bin/sh: brew: command not found
OpenSSL:
OpenSSL: exit code 0
GCC-Toolchain:printf "#if ((__GNUC__ << 16)+(__GNUC_MINOR__ << 8)+(__GNUC_PATCHLEVEL__) < (0x040800))\n#error \"Cannot use system's GCC.\"\n#endif\n" | gcc -xc++ - -c -o /dev/null
GCC-Toolchain:
GCC-Toolchain: exit code 0
boost:printf "#include \"boost/version.hpp\"\n# if (BOOST_VERSION < 105900)\n#error \"Cannot use system's boost.\"\n#endif" | gcc -I$(brew --prefix boost)/include -xc++ - -c -o /dev/null
/bin/sh: brew: command not found
<stdin>:3:2: error: #error "Cannot use system's boost."
boost:
boost: exit code 1
autotools:PATH=$PATH:$(brew --prefix gettext || true)/bin && which autoconf && which m4 && which automake && which makeinfo && which aclocal && which pkg-config && which autopoint && which libtool
/bin/sh: brew: command not found
autotools:/usr/bin/autoconf
autotools:/usr/bin/m4
autotools:/usr/bin/automake
autotools:/usr/bin/makeinfo
autotools:/usr/bin/aclocal
autotools:/usr/bin/pkg-config
autotools:/usr/bin/autopoint
autotools:/usr/bin/libtool
autotools:
autotools: exit code 0
SWIG:which swig
SWIG:/usr/bin/swig
SWIG:
SWIG: exit code 0
Python:python -c 'import matplotlib; import numpy; import certifi ; import sys; sys.exit(1 if sys.version_info < (2, 7) else 0)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named matplotlib
Python:
Python: exit code 1
zlib:printf "#include <zlib.h>\n" | gcc -xc++ - -c -o /dev/null
zlib:
zlib: exit code 0
libxml2:which xml2-config
libxml2:/usr/bin/xml2-config
libxml2:
libxml2: exit code 0
```

And here's the output of the other command:
```
[vasco@aidrefflp01 alice]$ printf "#include \"zmq.h\"\n" | gcc -I$(brew --prefix zeromq)/include -xc++ - -c -M
-bash: brew: command not found
-:  /usr/include/zmq.h /usr/include/errno.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h \
 /usr/include/gnu/stubs.h /usr/include/gnu/stubs-64.h \
 /usr/include/bits/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/asm-generic/errno.h \
 /usr/include/asm-generic/errno-base.h \
 /opt/rh/devtoolset-3/root/usr/lib/gcc/x86_64-redhat-linux/4.9.1/include/stddef.h \
 /usr/include/stdio.h /usr/include/bits/types.h \
 /usr/include/bits/typesizes.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/wchar.h \
 /opt/rh/devtoolset-3/root/usr/lib/gcc/x86_64-redhat-linux/4.9.1/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h \
 /opt/rh/devtoolset-3/root/usr/lib/gcc/x86_64-redhat-linux/4.9.1/include/stdint.h \
 /usr/include/stdint.h /usr/include/bits/wchar.h
```

**Comment by ktf** [comment]
In order for you to continue working, can you please simply uninstall zeromq from the system? alibuild should then notice and build it's own copy.

I will try to find a safe way to pick it up from the system (simply adding /usr to the search paths will not work, because that will mean it will potentially pick up from the system things which should not be picked up, i.e. we must make sure /usr comes last in the search path and I am not sure FairROOT will actually do that.)

**Comment by vascobarroso** [comment]
zeromq unistalled. 
Next error: [log](https://github.com/alisw/alidist/files/179446/log.txt)

**Comment by ktf** [comment]
This is actually wrong in AliceO2. o2qa fails to add ZMQ_INCLUDE_DIR to their `INCLUDE_DIRECTORIES`. Will propose a fix.

**Comment by ktf** [comment]
@Barthelemy @MattiasRichter this last issue is exactly what I am worried about regarding dependencies. If we let people do what they want in their CMakeLists, it's guaranteed that they will do things which work by accident only on their setup. If they had to declare their application as part of the QABucket, there would have been no way they could make this ambiguous.

**Comment by Barthelemy** [comment]
I see, good point. I think that we will find a good way of securing the deps. In addition it shows that we need CI builds on multiple platforms (here it would have failed for SLC6), [automatic detection of dependencies modifications] and human reviews.

**Comment by ktf** [comment]
Agreed we need integration builds (I am working on it right now, since looks like we have a bit more activity on O2) however we should limit the number of rebuilds because of errors which can be caught early. Each time a human or a bot checks things, it costs both time and money.

**Comment by ktf** [comment]
This I assume is fixed, right? For what concerns the "online environment" builds, you can find the related issue at alisw/docks#95 and alisw/docks#96.

**Comment by vascobarroso** [comment]
I can now build O2 on CC7, but haven't tried on SLC6.

**Comment by Barthelemy** [comment]
on SLC6 it still fails for me with the error 

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ZMQ_INCLUDE_DIR (ADVANCED)

I use the branch  IB/master/root6

**Comment by ktf** [comment]
The problem is that FairRoot does not allow for system ZeroMQ, so while we can support it on mac (because we use brew) we have no means to find where it is to be found on linux. We were discussing this with @MohammadAlTurany yesterday and I think we agreed the proper fix would be that FairRoot checks for the version of ZeroMQ found on the system and uses it if compatible. For the time being I will simply turn off system zeromq on linux (see #393).

**Comment by MohammadAlTurany** [comment]
Hallo,

This issue is solved in the FairRoot dev branch (https://github.com/FairRootGroup/FairRoot/pull/365). Can you update your FairRoot?

best,

Mohammad

**Comment by ktf** [comment]
At the moment we track `master` for FairRoot. As discussed I will switch to `dev`.

**Comment by ktf** [comment]
This was fixed a while ago. Closing.
