### ISSUE TITLE
O2 build needs gettext-0.18.3 but CC7 has 18.2.1

### ISSUE THREAD

**Issue by vascobarroso** [alisw/alidist#277]
Trying to build O2 on CC7 fails due to old gettext version (see [log](https://github.com/alisw/alidist/files/206732/log.txt)).

I'm using branch IB/v5-08/next.

**Comment by ktf** [comment]
Should be fixed in #281. Please pull from IB/v5-08/next. Will be merged in IB/v5-08/prod as soon as we get a new production release. Reopen if you have troubles.

**Comment by Barthelemy** [comment]
Problem is still there for me. 
alibuild : next
alidist :  IB/v5-08/next
devtoolset : no 
OS : CC7
[log.txt](https://github.com/alisw/alidist/files/230171/log.txt)
